### PR TITLE
Update zabbix_php_fpm_template.xml

### PR DESCRIPTION
**Pull request by LeoShivas**
Replace vsize by rss because it's more relevant in monitoring.

### CODE REVIEW

**Comment by rvalitov** [comment]
Thank you for your contribution. Can you please explain why `rss` is more relevant?
My logic is that `vsize` shows the total memory used by PHP, while `rss` shows only a portion of used memory that is currently in RAM. `rss` is less or equal to `vsize`, because some portions of memory can be in swap file, not only in RAM. 

For example, one PHP pool N1 may have 32 Mb in RAM (`rss`=32Mb) and 100 Mb in swap, i.e. `vsize`=132 Mb, another PHP pool N2 may have `rss`=64Mb and 0 Mb in swap, `vsize`=64 Mb. If you operate with `rss` then you may think that PHP pool N1 uses less memory than PHP pool N2, but that's completely wrong.

Therefore, the question is what's the benefit to know the `rss`?

**Comment by LeoShivas** [comment]
Hi @rvalitov,

Thanks for your work.

As indicated in the manpage from `top` :
```
36. VIRT  --  Virtual Memory Size (KiB)
           The total amount of virtual memory used by the task.  It includes all code, data and
shared libraries plus pages that have been swapped out and pages that have been mapped but not
used.

```

For example, here is my top command with the process php-fpm :
```
top - 18:05:43 up 8 days,  9:23,  2 users,  load average: 0,01, 0,05, 0,11
Tasks: 223 total,   1 running, 222 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2,8 us,  0,7 sy,  0,0 ni, 96,0 id,  0,4 wa,  0,0 hi,  0,1 si,  0,0 st
KiB Mem :  3880336 total,   176324 free,  1820140 used,  1883872 buff/cache
KiB Swap:  2097148 total,  2040328 free,    56820 used.  1568244 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6301 php-fpm   20   0  543400  25048   9584 S   5,0  0,6   0:10.22 php-fpm
17836 php-fpm   20   0  543656  24680  10012 S   3,0  0,6   1:02.78 php-fpm
17745 php-fpm   20   0  543460  24452   9708 S   2,7  0,6   1:02.13 php-fpm
 2145 php-fpm   20   0  274124   3912    728 S   0,0  0,1   0:00.00 php-fpm
 2146 php-fpm   20   0  274124   3916    728 S   0,0  0,1   0:00.00 php-fpm
 7100 php-fpm   20   0  549788  32024  10436 S   0,0  0,8   0:00.27 php-fpm
10159 php-fpm   20   0  407848   9656   1420 S   0,0  0,2   0:00.00 php-fpm
10160 php-fpm   20   0  407848   9656   1420 S   0,0  0,2   0:00.00 php-fpm
10161 php-fpm   20   0  407848   9640   1412 S   0,0  0,2   0:00.00 php-fpm
10162 php-fpm   20   0  407848   9640   1412 S   0,0  0,2   0:00.00 php-fpm
10163 php-fpm   20   0  541316  21672   8248 S   0,0  0,6   0:08.19 php-fpm
10164 php-fpm   20   0  541316  21672   8248 S   0,0  0,6   0:08.13 php-fpm
10165 php-fpm   20   0  407848   9640   1412 S   0,0  0,2   0:00.00 php-fpm
10166 php-fpm   20   0  407848   9640   1412 S   0,0  0,2   0:00.00 php-fpm
10167 php-fpm   20   0  552884  34844  11304 S   0,0  0,9   0:02.58 php-fpm
10168 php-fpm   20   0  560832  47844  15524 S   0,0  1,2   0:02.44 php-fpm
10169 php-fpm   20   0  541300  20820   8852 S   0,0  0,5   0:00.18 php-fpm
10170 php-fpm   20   0  539252  20212   8844 S   0,0  0,5   0:00.11 php-fpm
10171 php-fpm   20   0  613004  17856   8388 S   0,0  0,5   0:00.08 php-fpm
10172 php-fpm   20   0  613000  17816   8364 S   0,0  0,5   0:00.02 php-fpm

```
And here my memory :
```
              total        used        free      shared  buff/cache   available
Mem:           3789        1777         162         198        1849        1531
Swap:          2047          55        1992

```

As you can see, the amount of vsize is huge, according to the numbers of "all code, data and shared libraries plus pages that have been swapped out and pages that have been mapped but not used."

So, vsize IS NOT RAM +swap.

Here is the graph I obtained by modifying your template :
image

This fully meets my needs !

**Comment by rvalitov** [comment]
Thank you for a prompt response and the example. I will check further about the virtual memory. In my case I have a similar output of `top` as yours. So, I thought it was correct, because I have `memory_limit=128Mb` in PHP, and I have 4 children in a pool, so each pool's virtual memory is about 4x128Mb=around 500 Mb, plus shared code and libs used by the PHP (the more PHP extensions you have enabled, the more memory consumption each PHP pool will have). That's why one pool may easily consume half of GB of memory. If the pool is inactive, then Linux swaps it and removes from RAM. But if I sum up all virtual memory from your `top` command, then it's much more than just RAM + swap, indeed. So, `RES` from `top` equals to `rss` from Zabbix?

**Comment by LeoShivas** [comment]
That's right.

`RES` from top :
```
       17. RES  --  Resident Memory Size (KiB)
           The non-swapped physical memory a task is using.

```

and `rss` from Zabbix (https://www.zabbix.com/documentation/4.4/manual/appendix/items/proc_mem_notes#linux) :

rss | Resident set size | VmRSS
-- | -- | --

That's why I think it's more relevant.
If you want to keep vsize, you can add a rss item to your template ?

**Pull request merged**
