### PR TITLE
Improved alias safe method to get commands and locations of required executables

### PR DESCRIPTION
**Pull request by carlheaton**
Alias safe which

### CODE REVIEW

**Comment by rvalitov** [comment]
Hello! Thank you very much for your contribution. I checked `man which` at Debian 9.11 (stretch) and the ` --skip-alias` option is not available there:

image

Some people specify that this option is not available also in Ubuntu. Others say that it's not available in any `zsh`.

Some recommend to use another approach instead of `which` - `type` and/or `command`, see https://unix.stackexchange.com/a/10529 and https://stackoverflow.com/a/677212

What do you think about that?

Can you please share for what environment and OS did you use the `--skip-alias` option? Did you face a problem with aliases, i.e. the script didn't work without your updates?

**Comment by carlheaton** [comment]
`[root@removed ~]# which grep
**alias grep='grep --color=auto'**
	/usr/bin/grep

This did break the script due to the line above path.

The script worked perfectly (thank you) when corrected.

[root@removed ~]# cat /etc/os-release 
NAME="**CentOS** Linux"
VERSION="**7** (Core)"

[root@removed ~]# uname -a
Linux removed 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

Agree maybe consider alternate if multi-platform safe:

`[root@removed ~]# type -P grep
/usr/bin/grep
`

On an unrelated note that's not your problem but may be useful for other, I spent ages debugging:

`[root@removed zabbix]# sh zabbix_php_fpm_discovery.sh
zabbix_php_fpm_discovery.sh: line 42: syntax error near unexpected token `<'
zabbix_php_fpm_discovery.sh: line 42: `mapfile -t PS_LIST < <( $S_PS ax | $S_GREP "php-fpm: pool " | $S_GREP -v grep )'
`

Only to find it should of been:

`bash zabbix_php_fpm_discovery.sh`

**Comment by rvalitov** [comment]
Thank you for your tests and information. I also tested `type -P` and it works great. If you can kindly change your current PR or make a new one to work with `type` then I will happily merge it.

Regarding the `bash zabbix_php_fpm_discovery.sh` - thank you for the info! I will add a related notice in the README.

**Comment by carlheaton** [comment]
I think that pull should be updated now?

If updating readme could also tweak:

`apt-get -y install grep gawk lsof jq libfcgi0ldbl
`
`yum install grep gawk lsof jq fcgi
`

**Comment by rvalitov** [comment]
Thank very much for your contribution and valuable comments!

**Pull request merged**
